### ISSUE TITLE
远程控制功能无法使用

### ISSUE THREAD

**Issue by Donoy** [kuan1/electron-remote-control#22]
hi，朋友，我看到你这个例子，我在本地（windows）能够成功运行（**点赞~**）---

1、我在本地启动两个客户端，A和B
2、在A中输入B中显示的“控制码”之后，A客户端的程序界面进入到黑色的屏幕之后，就没有任何回应了..
3、于是打开调试工具，查看到一条“socket关闭的”日志
4、查看源代码发现，客户端在启动的时候，会使用websocket连接 wss://www.luzhongkuan.cn/websocket?code=${user.code}，但是我本地不存在这样的websocket服务端，可能是由于这个导致“远程控制”无法使用，在代码中搜索WebSocket关键字，也仅仅只有socket.js这个文件下使用....

想问问你这个websocket服务器是没有公开，又或者是公开了我使用的方式不对，希望能够收到你的回复，谢谢~

**Comment by kuan1** [comment]
@Donoy 这个demo是通过webrtc来实现的，websocket(临时公开服务)是的作用只是用来交换凭证，然后通过robotjs控制鼠标，如果测试的话可用两台电脑，如果你通过一台电脑可能感觉不到鼠标的控制（不过延迟比较严重，代码仅供参考）。

如果你想看实现原理，你可以看下这个git仓库中的代码，[WebRTC-Experiment](https://github.com/muaz-khan/WebRTC-Experiment/tree/master/DataChannel)。
